let mots=[/*'SUCRERIES','GUITARE','CASQUE','PLUSPLUS','VOITURE','LEGO','BONBON','CHOCOLAT','FLUTE','CIDRE','PIANO','SUCETTE','PENDU',*/
'ABACOST','ABACULE','ABAISSA','ABAISSE','ABAJOUE','ABALONE','ABANDON','ABAQUES','ABASIES','ABATAGE','ABATANT','ABATEES','ABATTEE','ABATTES','ABATTEZ','ABATTIS','ABATTIT',
'ABATTRA','ABATTRE','ABATTUE','ABATTUS','ABBAYES','ABBESSE','ABCEDAI','ABCEDAS','ABCEDAT','ABCEDEE','ABCEDER','ABCEDES','ABCEDEZ','ABDIQUA','ABDIQUE','ABDOMEN','ABEILLE',
'ABELIAS','ABELIEN','ABELIES','ABERRAI','ABERRAS','ABERRAT','ABERRER','ABERRES','ABERREZ','ABESSIF','ABETIES','ABETIRA','ABHORRA','ABHORRE','ABIETIN','ABIMAIS','ABIMAIT',
'ABIMANT','ABIMEES','ABIMENT','ABIMERA','ABIMIEZ','ABIMONS','ABJECTE','ABJECTS','ABJURAI','ABJURAS','ABJURAT','ABJUREE','ABJURER','ABJURES','ABJUREZ','ABKHAZE','ABLATAI',
'ABLATAS','ABLATAT','ABLATEE','ABLATER','ABLATES','ABLATEZ','ABLATIF','ABLEGAT','ABLERET','ABLETTE','ABLIERS','ABLOQUA','ABLOQUE','ABOIENT','ABOIERA','ABOLIES','ABOLIRA',
'ABOMINA','ABOMINE','ABONDAI','ABONDAS','ABONDAT','ABONDEE','ABONDER','ABONDES','ABONDEZ','ABONNAI','ABONNAS','ABONNAT','ABONNEE','ABONNER','ABONNES','ABONNEZ','ABONNIE',
'ABONNIR','ABONNIS','ABONNIT','ABORDAI','ABORDAS','ABORDAT','ABORDEE','ABORDER','ABORDES','ABORDEZ','ABORNAI','ABORNAS','ABORNAT','ABORNEE','ABORNER','ABORNES','ABORNEZ',
'ABORTIF','ABOTEAU','ABOUCHA','ABOUCHE','ABOULAI','ABOULAS','ABOULAT','ABOULEE','ABOULER','ABOULES','ABOULEZ','ABOULIE','ABOUTAI','ABOUTAS','ABOUTAT','ABOUTEE','ABOUTER',
'ABOUTES','ABOUTEZ','ABOUTIE','ABOUTIR','ABOUTIS','ABOUTIT','ABOYAIS','ABOYAIT','ABOYANT','ABOYEES','ABOYEUR','ABOYIEZ','ABOYONS','ABRASAI','ABRASAS','ABRASAT','ABRASEE',
'ABRASER','ABRASES','ABRASEZ','ABRASIF','ABRAXAS','ABREAGI','ABREGEA','ABREGEE','ABREGER','ABREGES','ABREGEZ','ABREUVA','ABREUVE','ABRIAIS','ABRIAIT','ABRIANT','ABRIBUS',
'ABRICOT','ABRIEES','ABRIENT','ABRIERA','ABRIIEZ','ABRIONS','ABRITAI','ABRITAS','ABRITAT','ABRITEE','ABRITER','ABRITES','ABRITEZ','ABROGEA','ABROGEE','ABROGER','ABROGES',
'ABROGEZ','ABROUTI','ABRUPTE','ABRUPTS','ABRUTIE','ABRUTIR','ABRUTIS','ABRUTIT','ABSCONS','ABSENCE','ABSENTA','ABSENTE','ABSENTS','ABSIDAL','ABSIDES','ABSOLUE','ABSOLUS',
'ABSOLUT','ABSOLVE','ABSORBA','ABSORBE','ABSOUTE','ABSOUTS','ABSTEME','ABSTENU','ABSTINS','ABSTINT','ABSTRUS','ABSURDE','ABUSAIS','ABUSAIT','ABUSANT','ABUSEES','ABUSENT',
'ABUSERA','ABUSEUR','ABUSIEZ','ABUSIFS','ABUSIVE','ABUSONS','ABUTAIS','ABUTAIT','ABUTANT','ABUTEES','ABUTENT','ABUTERA','ABUTIEZ','ABUTONS','ABYSSAL','ABYSSES','ABYSSIN',
'ABZYMES','ACABITS','ACACIAS','ACADIEN','ACAJOUS','ACANTHE','ACARIEN','ACARPES','ACATENE','ACAULES','ACCABLA','ACCABLE','ACCEDAI','ACCEDAS','ACCEDAT','ACCEDER','ACCEDES',
'ACCEDEZ','ACCENTS','ACCEPTA','ACCEPTE','ACCISES','ACCLAMA','ACCLAME','ACCOLAI','ACCOLAS','ACCOLAT','ACCOLEE','ACCOLER','ACCOLES','ACCOLEZ','ACCORAI','ACCORAS','ACCORAT',
'ACCORDA','ACCORDE','ACCORDS','ACCOREE','ACCORER','ACCORES','ACCOREZ','ACCORNE','ACCORTE','ACCORTS','ACCOSTA','ACCOSTE','ACCOTAI','ACCOTAS','ACCOTAT','ACCOTEE','ACCOTER',
'ACCOTES','ACCOTEZ','ACCOUAI','ACCOUAS','ACCOUAT','ACCOUDA','ACCOUDE','ACCOUEE','ACCOUER','ACCOUES','ACCOUEZ','ACCOURE','ACCOURS','ACCOURT','ACCOURU','ACCOUVA','ACCOUVE',
'ACCREEN','ACCRETA','ACCRETE','ACCROCS','ACCROIS','ACCROIT','ACCRUES','ACCUEIL','ACCULAI','ACCULAS','ACCULAT','ACCULEE','ACCULER','ACCULES','ACCULEZ','ACCUSAI','ACCUSAS',
'ACCUSAT','ACCUSEE','ACCUSER','ACCUSES','ACCUSEZ','ACEDIES','ACENSAI','ACENSAS','ACENSAT','ACENSEE','ACENSER','ACENSES','ACENSEZ','ACERAIS','ACERAIT','ACERANT','ACERBES',
'ACEREES','ACERENT','ACERERA','ACERIEZ','ACEROLA','ACEROLE','ACERONS','ACETALS','ACETATE','ACETEUX','ACETONE','ACETYLA','ACETYLE','ACHAINE','ACHALAI','ACHALAS','ACHALAT',
'ACHALEE','ACHALER','ACHALES','ACHALEZ','ACHANTI','ACHARDS','ACHARNA','ACHARNE','ACHEENS','ACHENES','ACHETAI','ACHETAS','ACHETAT','ACHETEE','ACHETER','ACHETES','ACHETEZ',
'ACHEVAI','ACHEVAS','ACHEVAT','ACHEVEE','ACHEVER','ACHEVES','ACHEVEZ','ACHIGAN','ACHIRAL','ACHOLIE','ACHOPPA','ACHOPPE','ACHOURA','ACHROME','ACHYLIE','ACIDAGE','ACIDITE',
'ACIDOSE','ACIDULA','ACIDULE','ACIERAI','ACIERAS','ACIERAT','ACIEREE','ACIERER','ACIERES','ACIEREZ','ACIERIE','ACINEUX','ACOLYTE','ACOMPTE','ACONAGE','ACONIER','ACONITS',
'ACOREEN','ACORIEN','ACOUCHI','ACQUETS','ACQUISE','ACQUITS','ACRETES','ACTAMES','ACTANTS','ACTASSE','ACTATES','ACTERAI','ACTERAS','ACTEREZ','ACTEURS','ACTINES','ACTINIE',
'ACTIONS','ACTIVAI','ACTIVAS','ACTIVAT','ACTIVEE','ACTIVER','ACTIVES','ACTIVEZ','ACTORAT','ACTRICE','ACTUELS','ACUITES','ACUMINE','ADAGIOS','ADAMAWA','ADAMIEN','ADAMITE',
'ADAPTAI','ADAPTAS','ADAPTAT','ADAPTEE','ADAPTER','ADAPTES','ADAPTEZ','ADDENDA','ADDICTE','ADDICTS','ADDITIF','ADDUITS','ADENINE','ADENITE','ADENOME','ADEPTES','ADEQUAT',
'ADESSIF','ADEXTRE','ADHERAI','ADHERAS','ADHERAT','ADHERER','ADHERES','ADHEREZ','ADHESIF','ADIANTE','ADIPEUX','ADIPOSE','ADIPSIE','ADIREES','ADITION','ADIVASI','ADJARES',
'ADJOINS','ADJOINT','ADJUGEA','ADJUGEE','ADJUGER','ADJUGES','ADJUGEZ','ADJURAI','ADJURAS','ADJURAT','ADJUREE','ADJURER','ADJURES','ADJUREZ','ADJUVAT','ADMETTE','ADMIMES',
'ADMIRAI','ADMIRAS','ADMIRAT','ADMIREE','ADMIRER','ADMIRES','ADMIREZ','ADMISES','ADMISSE','ADMITES','ADONIDE','ADONIEN','ADONIES','ADONNAI','ADONNAS','ADONNAT','ADONNEE',
'ADONNER','ADONNES','ADONNEZ','ADOPTAI','ADOPTAS','ADOPTAT','ADOPTEE','ADOPTER','ADOPTES','ADOPTEZ','ADOPTIF','ADORAIS','ADORAIT','ADORANT','ADOREES','ADORENT','ADORERA',
'ADORIEZ','ADORNAI','ADORNAS','ADORNAT','ADORNEE','ADORNER','ADORNES','ADORNEZ','ADORONS','ADOSSAI','ADOSSAS','ADOSSAT','ADOSSEE','ADOSSER','ADOSSES','ADOSSEZ','ADOUBAI',
'ADOUBAS','ADOUBAT','ADOUBEE','ADOUBER','ADOUBES','ADOUBEZ','ADOUCIE','ADOUCIR','ADOUCIS','ADOUCIT','ADRESSA','ADRESSE','ADROITE','ADROITS','ADSCRIT','ADSORBA','ADSORBE',
'ADSTRAT','ADULAIS','ADULAIT','ADULANT','ADULEES','ADULENT','ADULERA','ADULIEZ','ADULONS','ADULTES','ADVENIR','ADVENUE','ADVENUS','ADVERBE','ADVERSE','ADVIENT','ADYTONS',
'AERAGES','AERAMES','AERASSE','AERATES','AERERAI','AERERAS','AEREREZ','AERIENS','AERIONS','AERIUMS','AEROBIC','AEROBIE','AEROBUS','AEROGEL','AERONEF','AEROSOL','AESCHNE',
'AETHUSA','AETHUSE','AETITES','AFFABLE','AFFADIE','AFFADIR','AFFADIS','AFFADIT','AFFAIRA','AFFAIRE','AFFAITA','AFFAITE','AFFALAI','AFFALAS','AFFALAT','AFFALEE','AFFALER',
'AFFALES','AFFALEZ','AFFAMAI','AFFAMAS','AFFAMAT','AFFAMEE','AFFAMER','AFFAMES','AFFAMEZ','AFFEAGE','AFFECTA','AFFECTE','AFFECTS',
'AFFERAI','AFFERAS','AFFERAT','AFFERER','AFFERES','AFFEREZ','AFFERMA','AFFERME','AFFERMI','AFFETEE','AFFETES','AFFIANT','AFFICHA','AFFICHE','AFFIDEE','AFFIDES','AFFILAI',
'AFFILAS','AFFILAT','AFFILEE','AFFILER','AFFILES','AFFILEZ','AFFILIA','AFFILIE','AFFINAI','AFFINAS','AFFINAT','AFFINEE','AFFINER','AFFINES','AFFINEZ','AFFIRMA','AFFIRME',
'AFFIXAL','AFFIXEE','AFFIXES','AFFLIGE','AFFLOUA','AFFLOUE','AFFLUAI','AFFLUAS','AFFLUAT','AFFLUER','AFFLUES','AFFLUEZ','AFFOLAI','AFFOLAS','AFFOLAT','AFFOLEE','AFFOLER',
'AFFOLES','AFFOLEZ','AFFRETA','AFFRETE','AFFREUX','AFFRONT','AFFUBLA','AFFUBLE','AFFUTAI','AFFUTAS','AFFUTAT','AFFUTEE','AFFUTER','AFFUTES','AFFUTEZ','AFGHANE','AFGHANI',
'AFGHANS','AFICION','AFOCALE','AFOCAUX','AGACAIS','AGACAIT','AGACANT','AGACEES','AGACENT','AGACERA','AGACIEZ','AGACONS','AGAMETE','AGAMIDE','AGAMIES','AGAPETE','AGARICS',
'AGAROSE','AGASSES','AGASSIN','AGATISE','AGENAIS','AGENCAI','AGENCAS','AGENCAT','AGENCEE','AGENCER','AGENCES','AGENCEZ','AGENDAI','AGENDAS','AGENDAT','AGENDEE','AGENDER',
'AGENDES','AGENDEZ','AGENOIS','AGENTES','AGENTIF','AGERATE','AGETACS','AGGADAH','AGGRAVA','AGGRAVE','AGILITE','AGILITY','AGIOTAI','AGIOTAS','AGIOTAT','AGIOTER','AGIOTES',
'AGIOTEZ','AGIRAIS','AGIRAIT','AGIRENT','AGIRIEZ','AGIRONS','AGIRONT','AGISMES','AGISSES','AGISSEZ','AGITAIS','AGITAIT','AGITANT','AGITATO','AGITEES','AGITENT','AGITERA',
'AGITIEZ','AGITONS','AGLOSSA','AGLOSSE','AGLYPHE','AGNATES','AGNATHE','AGNEAUX','AGNELAI','AGNELAS','AGNELAT','AGNELEE','AGNELER','AGNELES','AGNELET','AGNELEZ','AGNELIN',
'AGNELLE','AGNOSIE','AGONALE','AGONAUX','AGONIES','AGONIRA','AGONISA','AGONISE','AGOUTIS','AGRAFAI','AGRAFAS','AGRAFAT','AGRAFEE','AGRAFER','AGRAFES','AGRAFEZ','AGRAINA',
'AGRAINE','AGRAIRE','AGRANDI','AGREAGE','AGREAIS','AGREAIT','AGREANT','AGREEES','AGREENT','AGREERA','AGREEUR','AGREGAT','AGREGEA','AGREGEE','AGREGER','AGREGES','AGREGEZ',
'AGREIEZ','AGREONS','AGRESSA','AGRESSE','AGRESTE','AGRIFFA','AGRIFFE','AGRILES','AGRIONS','AGRIOTE','AGRIPPA','AGRIPPE','AGROTIS','AGRUMES','AGUERRI','AGUICHA','AGUICHE',
'AGUILLA','AGUILLE','AHANAIS','AHANAIT','AHANANT','AHANENT','AHANERA','AHANIEZ','AHANONS','AHEURTA','AHEURTE','AHURIES','AHURIRA','AICHAIS','AICHAIT','AICHANT','AICHEES',
'AICHENT','AICHERA','AICHIEZ','AICHONS','AIDAMES','AIDANTE','AIDANTS','AIDASSE','AIDATES','AIDEAUX','AIDERAI','AIDERAS','AIDEREZ','AIDIONS','AIEULES','AIGAGES','AIGLONS',
'AIGNELS','AIGREUR','AIGRIES','AIGRINS','AIGRIRA','AIGUADE','AIGUAGE','AIGUAIL','AIGUISA','AIGUISE','AIKIDOS','AILANTE','AILERON','AILETTE','AILIERE','AILIERS','AILLADE',
'AILLAIS','AILLAIT','AILLANT','AILLEES','AILLENT','AILLERA','AILLETS','AILLIEZ','AILLOLI','AILLONS','AIMABLE','AIMAMES','AIMANTA','AIMANTE','AIMANTS','AIMASSE','AIMATES',
'AIMERAI','AIMERAS','AIMEREZ','AIMIONS','AINESSE','AINOUES','AIRAINS','AIRAMES','AIRASSE','AIRATES','AIRBAGS','AIRELLE','AIRERAI','AIRERAS','AIREREZ','AIRIONS','AIRURES',
'AISANCE','AISSEAU','AIXOISE','AJACCIO','AJISTES','AJOINTA','AJOINTE','AJOUPAS','AJOURAI','AJOURAS','AJOURAT','AJOUREE','AJOURER','AJOURES','AJOUREZ','AJOURNA','AJOURNE',
'AJOUTAI','AJOUTAS','AJOUTAT','AJOUTEE','AJOUTER','AJOUTES','AJOUTEZ','AJUSTAI','AJUSTAS','AJUSTAT','AJUSTEE','AJUSTER','AJUSTES','AJUSTEZ','AJUTAGE','AKASSAS','AKUAVIT',
'AKVAVIT','ALAIRES','ALAISEE','ALAISES','ALAMBIC','ALANGUI','ALANINE','ALARMAI','ALARMAS','ALARMAT','ALARMEE','ALARMER','ALARMES','ALARMEZ','ALAWITE','ALBATRE','ALBEDOS',
'ALBERGE','ALBIENS','ALBINOS','ALBITES','ALBUGOS','ALBUMEN','ALCADES','ALCALIN','ALCALIS','ALCANES','ALCAZAR','ALCENES','ALCIDES','ALCOOLE','ALCOOLO','ALCOOLS','ALCORAN',
'ALCOVES','ALCOYLE','ALCYNES','ALCYONS','ALDINES','ALDOSES','ALENOIS','ALENTIE','ALENTIR','ALENTIS','ALENTIT','ALEOUTE','ALEPINE','ALEPINS','ALEPPIN','ALERION','ALERTAI',
'ALERTAS','ALERTAT','ALERTEE','ALERTER','ALERTES','ALERTEZ','ALESAGE','ALESAIS','ALESAIT','ALESANT','ALESEES','ALESENT','ALESERA','ALESEUR','ALESIEN','ALESIEZ','ALESOIR',
'ALESONS','ALESURE','ALEVIES','ALEVINA','ALEVINE','ALEVINS','ALEXIES','ALEXINE','ALEZANE','ALEZANS','ALEZEES','ALFALFA','ALFANGE','ALGALES','ALGEBRE','ALGIDES','ALGINES',
'ALGIQUE','ALIDADE','ALIENAI','ALIENAS','ALIENAT','ALIENEE','ALIENER','ALIENES','ALIENEZ','ALIFERE','ALIGNAI','ALIGNAS','ALIGNAT','ALIGNEE','ALIGNER','ALIGNES','ALIGNEZ',
'ALIGOTE','ALIGOTS','ALIMENT','ALINEAS','ALISIER','ALISMAS','ALISMES','ALITAIS','ALITAIT','ALITANT','ALITEES','ALITENT','ALITERA','ALITIEZ','ALITONS','ALIZARI','ALIZEEN',
'ALIZIER','ALKYLES','ALLACHE','ALLAITA','ALLAITE','ALLAMES','ALLANTE','ALLANTS','ALLASSE','ALLATES','ALLATIF','ALLECHA','ALLECHE','ALLEGEA','ALLEGEE','ALLEGER','ALLEGES',
'ALLEGEZ','ALLEGIE','ALLEGIR','ALLEGIS','ALLEGIT','ALLEGRE','ALLEGRO','ALLEGUA','ALLEGUE','ALLELES','ALLENES','ALLIACE','ALLIAGE','ALLIAIS','ALLIAIT','ALLIANT','ALLIEES',
'ALLIENT','ALLIERA','ALLIIEZ','ALLIONS','ALLONGE','ALLOTIE','ALLOTIR','ALLOTIS','ALLOTIT','ALLOUAI','ALLOUAS','ALLOUAT','ALLOUEE','ALLOUER','ALLOUES','ALLOUEZ','ALLUMAI',
'ALLUMAS','ALLUMAT','ALLUMEE','ALLUMER','ALLUMES','ALLUMEZ','ALLUREE','ALLURES','ALLUSIF','ALLYLES','ALMELEC','ALOGIES','ALOUATE','ALOUCHE','ALOURDI','ALOYAUX','ALPACAS',
'ALPAGAS','ALPAGES','ALPAGUA','ALPAGUE','ALPAMES','ALPASSE','ALPATES','ALPERAI','ALPERAS','ALPEREZ','ALPINES','ALPINIA','ALPIONS','ALPISTE','ALSACES','ALTAIEN','ALTERAI',
'ALTERAS','ALTERAT','ALTEREE','ALTERER','ALTERES','ALTEREZ','ALTERNA','ALTERNE','ALTESSE','ALTHAEA','ALTHEAS','ALTHEES','ALTIERE','ALTIERS','ALTISES','ALTISTE','ALUCITE',
'ALUETTE','ALUMINA','ALUMINE','ALUMNAT','ALUMNUS','ALUNAGE','ALUNAIS','ALUNAIT','ALUNANT','ALUNEES','ALUNENT','ALUNERA','ALUNIES','ALUNIEZ','ALUNIRA','ALUNITE','ALUNONS',
'ALVEOLE','ALVINES','ALYSSES','ALYSSON','ALYSSUM','AMADINE','AMADOUA','AMADOUE','AMADOUS','AMAIGRI','AMANCHA','AMANCHE','AMANDEE','AMANDES','AMANITE','AMANTES','AMARILE',
'AMARILS','AMARINA','AMARINE','AMARRAI','AMARRAS','AMARRAT','AMARREE','AMARRER','AMARRES','AMARREZ','AMASSAI','AMASSAS','AMASSAT','AMASSEE','AMASSER','AMASSES','AMASSEZ',
'AMATEUR','AMATHIE','AMATIES','AMATIRA','AMAZIGH','AMAZONE','AMBAGES','AMBIANT','AMBIFIA','AMBIFIE','AMBIGUE','AMBIGUS','AMBITUS','AMBLAIS','AMBLAIT','AMBLANT','AMBLENT',
'AMBLERA','AMBLEUR','AMBLIEZ','AMBLONS','AMBOINE','AMBRAIS','AMBRAIT','AMBRANT','AMBREES','AMBRENT','AMBRERA','AMBRIEZ','AMBRONS',
];

var good = new Set();
var bad = new Set();

let nbRound;
function hint(){
	if (good.size+bad.size<4||good.size+bad.size===nbRound) {
		return;
	}
	nbRound=good.size+bad.size;
	let pat=$('#mot').text();
	let goodLetters=[...good].join('');
	let re1=new RegExp('^'+pat.replaceAll('\.','[^'+goodLetters+']')+'$');
	let re2=new RegExp('['+$('#lettres').text()+']');
	$('#hint').text(mots.filter(x=>re1.test(x)&&!re2.test(x)));
}

$(document).ready(function() {

	let mot=mots[Math.floor(Math.random()*mots.length)];
  
	for (let i = 0; i<mot.length; i+=1){
		$('#mot').append('<div id="l'+i+'">.</div>');
	}
	
	$('body').on('keyup',keyup);
	$('#hintcont').on('mouseover',hint);

	function keyup(){
		let l=event.key.toUpperCase();
		if(!/^[A-Z]$/.test(l)||bad.size>10) {
			return;
		}
		if (mot.includes(l)) {
			reveal(l);
		} else {
			used(l);
		}
	}

	function reveal(l){
		if ( good.has(l)) {
			return;
		}
		good.add(l);
		Array.from(mot).forEach((c,i)=>{
			if (c===l){
				$('#l'+i).text(l);
			}
		});
		let gagne=/^\w+$/.test($('#mot').text());
		if (gagne){
			$('#nbTry').text('BRAVO !');
			document.body.onkeyup='';
		}
	}

	function used(l){
		if (bad.has(l)) {
			return;
		}
		bad.add(l);
		$('#lettres').append("<div>"+l+"</div>");
		let nbTry = 11-bad.size;
		$('#nbTry').text(nbTry<1?'PERDU ! le mot était '+mot:'Nombre d\'essais restants: '+nbTry);
		drawCanvas();
	}

});

function drawCanvas() {
	let canvas = $('#canvas');
	let nbe=bad.size;
	if (nbe===1) {
		canvas.drawRect({
			fillStyle: 'steelblue',
			strokeStyle: 'blue',
			strokeWidth: 2,
			x: 25, y: 270,
			fromCenter: false,
			width: 350, height: 20
		});
	} else if (nbe===2) {
		canvas.drawRect({
			fillStyle: 'pink',
			strokeStyle: '#a74ac7',
			strokeWidth: 2,
			x: 40, y: 25,
			fromCenter: false,
			width: 15, height: 245
		});
	} else if (nbe===3) {
		canvas.drawRect({
			fillStyle: 'pink',
			strokeStyle: '#a74ac7',
			strokeWidth: 2,
			x: 40, y: 10,
			fromCenter: false,
			width: 185, height: 15
		});
	} else if (nbe===4) {
		canvas.drawPath({
			fillStyle: 'pink',
			strokeStyle: '#a74ac7',
			strokeWidth: 2,
			p1: {
				type: 'line',
				x1: 55,  y1: 70,
				x2: 55,  y2: 50,
				x3: 80,  y3: 25,
				x4: 100, y4: 25,
				x5: 55,  y5: 70,
			}
		});
	} else if (nbe===5) {
		canvas.drawRect({
			fillStyle: 'chocolate',
			strokeStyle: 'maroon',
			strokeWidth: 2,
			x: 195, y: 25,
			fromCenter: false,
			width: 10, height: 30
		});
	} else if (nbe===6) {
		canvas.drawArc({
			fillStyle: 'grey',
			strokeStyle: 'black',
			strokeWidth: 2,
			x: 200, y: 78,
			radius: 20
		});
	} else if (nbe===7) {
		canvas.drawRect({
			fillStyle: 'grey',
			strokeStyle: 'black',
			strokeWidth: 2,
			x: 200, y: 126,
			width: 20, height: 50
		});
	} else if (nbe===8) {
		canvas.drawRect({
			fillStyle: 'grey',
			strokeStyle: 'black',
			strokeWidth: 2,
			x: 181, y: 127,
			width: 10, height: 50
		});
	} else if (nbe===9) {
		canvas.drawRect({
			fillStyle: 'grey',
			strokeStyle: 'black',
			strokeWidth: 2,
			x: 219, y: 127,
			width: 10, height: 50
		});
	} else if (nbe===10) {
		canvas.drawRect({
			fillStyle: 'grey',
			strokeStyle: 'black',
			strokeWidth: 2,
			x: 193, y: 184,
			width: 10, height: 60
		});
	} else if (nbe===11) {
		canvas.drawRect({
			fillStyle: 'grey',
			strokeStyle: 'black',
			strokeWidth: 2,
			x: 207, y: 184,
			width: 10, height: 60
		});
	}
}